import type { LearningAction, Profile, ProgressSnapshot } from "../types";
import { scheduleReview } from "./srs";
const prefix = "turkish-is-easy-v2::";
export const emptyProgress = (): ProgressSnapshot => ({ schemaVersion: 2, completedLessonIds: [], completedTopicIds: [], actionLog: {}, review: [], activityDates: [] });
export function storageKey(profile: Profile) { return `${prefix}${profile.id}::${profile.locale}::${profile.mode}`; }
export function migrateLegacy(profile: Profile): ProgressSnapshot | null { const keys = [`tie_v1_progress__${profile.id}__${profile.locale}__${profile.mode}`, `tmb_rc6_progress__${profile.id}__${profile.locale}__${profile.mode}`]; for (const key of keys) { const raw = localStorage.getItem(key); if (!raw) continue; try { const old = JSON.parse(raw) as { completedLessonIds?: string[]; completed?: string[]; completedIds?: string[]; activityDates?: string[] }; return { ...emptyProgress(), completedLessonIds: old.completedLessonIds ?? old.completed ?? old.completedIds ?? [], activityDates: old.activityDates ?? [] }; } catch { return null; } } return null; }
export function loadProgress(profile: Profile): ProgressSnapshot { try { const raw = localStorage.getItem(storageKey(profile)); if (raw) return { ...emptyProgress(), ...(JSON.parse(raw) as Partial<ProgressSnapshot>) }; const migrated = migrateLegacy(profile); if (migrated) { saveProgress(profile, migrated); return migrated; } } catch { /* local storage can be unavailable */ } return emptyProgress(); }
export function saveProgress(profile: Profile, progress: ProgressSnapshot) { try { localStorage.setItem(storageKey(profile), JSON.stringify(progress)); } catch { /* local-only preview */ } }
export function applyAction(progress: ProgressSnapshot, lessonId: string, action: LearningAction, today: string): ProgressSnapshot { const existing = progress.review.find((entry) => entry.lessonId === lessonId); const review = action === "needs_practice" ? [...progress.review.filter((entry) => entry.lessonId !== lessonId), scheduleReview(lessonId, existing, today, "needs_practice")] : progress.review; return { ...progress, completedLessonIds: progress.completedLessonIds.includes(lessonId) ? progress.completedLessonIds : [...progress.completedLessonIds, lessonId], actionLog: { ...progress.actionLog, [lessonId]: action }, review, activityDates: progress.activityDates.includes(today) ? progress.activityDates : [...progress.activityDates, today] }; }
