import type { LearningAction, Profile, ProgressSnapshot } from "../types";
import { realDayStreak, scheduleReview } from "./srs";
const prefix = "turkish-is-easy-v2::";
const STREAK_MILESTONES = [3, 7, 14, 30];
export const emptyProgress = (): ProgressSnapshot => ({ schemaVersion: 3, completedLessonIds: [], completedTopicIds: [], actionLog: {}, review: [], activityDates: [], dailyCounts: {}, streakMilestones: [] });
export function storageKey(profile: Profile) { return `${prefix}${profile.id}::${profile.locale}::${profile.mode}`; }
export function migrateLegacy(profile: Profile): ProgressSnapshot | null { const keys = [`tie_v1_progress__${profile.id}__${profile.locale}__${profile.mode}`, `tmb_rc6_progress__${profile.id}__${profile.locale}__${profile.mode}`]; for (const key of keys) { const raw = localStorage.getItem(key); if (!raw) continue; try { const old = JSON.parse(raw) as { completedLessonIds?: string[]; completed?: string[]; completedIds?: string[]; activityDates?: string[]; daily?: Record<string, number>; streak?: { milestones?: number[] }; items?: Record<string, { completed?: boolean; itemId?: string }> }; const completedFromItems = Object.values(old.items ?? {}).filter((item) => item.completed && item.itemId).map((item) => item.itemId as string); return { ...emptyProgress(), completedLessonIds: old.completedLessonIds ?? old.completed ?? old.completedIds ?? completedFromItems, activityDates: old.activityDates ?? Object.keys(old.daily ?? {}), dailyCounts: old.daily ?? {}, streakMilestones: old.streak?.milestones ?? [] }; } catch { return null; } } return null; }
function normalizeProgress(raw: Partial<ProgressSnapshot>): ProgressSnapshot { return { ...emptyProgress(), ...raw, schemaVersion: 3, dailyCounts: raw.dailyCounts ?? {}, streakMilestones: raw.streakMilestones ?? [] }; }
export function loadProgress(profile: Profile): ProgressSnapshot { try { const raw = localStorage.getItem(storageKey(profile)); if (raw) return normalizeProgress(JSON.parse(raw) as Partial<ProgressSnapshot>); const migrated = migrateLegacy(profile); if (migrated) { saveProgress(profile, migrated); return migrated; } } catch { /* local storage can be unavailable */ } return emptyProgress(); }
export function saveProgress(profile: Profile, progress: ProgressSnapshot) { try { localStorage.setItem(storageKey(profile), JSON.stringify(progress)); } catch { /* local-only preview */ } }
export function applyAction(progress: ProgressSnapshot, lessonId: string, action: LearningAction, today: string): ProgressSnapshot { const existing = progress.review.find((entry) => entry.lessonId === lessonId); const review = action === "needs_practice" ? [...progress.review.filter((entry) => entry.lessonId !== lessonId), scheduleReview(lessonId, existing, today, "needs_practice")] : progress.review; const firstCompletion = !progress.completedLessonIds.includes(lessonId); const activityDates = progress.activityDates.includes(today) ? progress.activityDates : [...progress.activityDates, today]; const dailyCounts = firstCompletion ? { ...progress.dailyCounts, [today]: (progress.dailyCounts[today] ?? 0) + 1 } : progress.dailyCounts; const streak = realDayStreak(activityDates, today); const streakMilestones = [...new Set([...progress.streakMilestones, ...STREAK_MILESTONES.filter((milestone) => milestone <= streak)])]; return { ...progress, schemaVersion: 3, completedLessonIds: firstCompletion ? [...progress.completedLessonIds, lessonId] : progress.completedLessonIds, actionLog: { ...progress.actionLog, [lessonId]: action }, review, activityDates, dailyCounts, streakMilestones }; }
export function resolveReview(progress: ProgressSnapshot, lessonId: string, successful: boolean, today: string): ProgressSnapshot { const existing = progress.review.find((entry) => entry.lessonId === lessonId); if (!existing) return applyAction(progress, lessonId, successful ? "practice_done" : "needs_practice", today); const activityDates = progress.activityDates.includes(today) ? progress.activityDates : [...progress.activityDates, today]; const streak = realDayStreak(activityDates, today); const streakMilestones = [...new Set([...progress.streakMilestones, ...STREAK_MILESTONES.filter((milestone) => milestone <= streak)])]; const rest = progress.review.filter((entry) => entry.lessonId !== lessonId); const review = successful ? (existing.step >= 3 ? rest : [...rest, scheduleReview(lessonId, existing, today, "scheduled")]) : [...rest, { lessonId, step: 0, dueOn: today, updatedAt: today, reason: "needs_practice" as const }]; return { ...progress, schemaVersion: 3, actionLog: { ...progress.actionLog, [lessonId]: successful ? "practice_done" : "needs_practice" }, review, activityDates, streakMilestones }; }
