import type { Lesson, Profile, Topic } from "../types";

const guide = (keyIdeaEn: string, keyIdeaId: string, hearEn: string, hearId: string, mistakeEn: string, mistakeId: string, practiceEn: string[], practiceId: string[]) => ({ keyIdea: { en: keyIdeaEn, id: keyIdeaId }, hear: { en: hearEn, id: hearId }, commonMistake: { en: mistakeEn, id: mistakeId }, miniPractice: { en: practiceEn, id: practiceId } });
const image = (name: string) => `/assets/${name}.png`;

export const PROFILES: Profile[] = [
  { id: "bella", name: "Bella", locale: "en", mode: "kids", badge: "B", description: { en: "English guidance · playful visual lessons", id: "Panduan bahasa Inggris · pelajaran visual" } },
  { id: "ayza", name: "Ayza", locale: "id", mode: "kids", badge: "A", description: { en: "Bahasa Indonesia guidance · playful visual lessons", id: "Panduan Bahasa Indonesia · pelajaran visual" } },
  { id: "adult", name: "Adult", locale: "en", mode: "adult", badge: "AD", description: { en: "English guidance · calm, focused practice", id: "Panduan bahasa Inggris · latihan tenang dan fokus" } },
  { id: "guest", name: "Guest", locale: "en", mode: "family", badge: "G", description: { en: "Try a short family learning session", id: "Coba sesi belajar keluarga singkat" } }
];

const roots: Lesson[] = [
  { id: "root_ev", kind: "recognition", prompt: { en: "Which Turkish word means house?", id: "Kata Turki mana yang berarti rumah?" }, finalWord: "ev", meaning: { en: "house", id: "rumah" }, options: ["ev", "su", "kitap"], answerParts: ["ev"], image: image("ev"), hint: [{ en: "Look at the home picture. The answer is short.", id: "Lihat gambar rumah. Jawabannya pendek." }], learnWhy: guide("Ev is the everyday word for house or home.", "Ev adalah kata sehari-hari untuk rumah.", "Keep the e open, then finish with a short v.", "Jaga bunyi e tetap terbuka, lalu akhiri dengan v pendek.", "Do not turn ev into a longer word.", "Jangan mengubah ev menjadi kata yang lebih panjang.", ["Look at a house.", "Say ev slowly."], ["Lihat rumah.", "Ucapkan ev perlahan."]) },
  { id: "root_kitap", kind: "recognition", prompt: { en: "Which Turkish word means book?", id: "Kata Turki mana yang berarti buku?" }, finalWord: "kitap", meaning: { en: "book", id: "buku" }, options: ["araba", "kitap", "ev"], answerParts: ["kitap"], image: image("kitap"), hint: [{ en: "Find the word that starts with ki-.", id: "Cari kata yang dimulai dengan ki-." }], learnWhy: guide("Kitap means book.", "Kitap berarti buku.", "Hear the clear final p in kitap.", "Dengarkan p yang jelas di akhir kitap.", "Do not split the word into English-like sounds.", "Jangan membagi kata menjadi bunyi seperti bahasa Inggris.", ["Point to a book.", "Say kitap."], ["Tunjuk sebuah buku.", "Ucapkan kitap."]) },
  { id: "root_araba", kind: "recognition", prompt: { en: "Which Turkish word means car?", id: "Kata Turki mana yang berarti mobil?" }, finalWord: "araba", meaning: { en: "car", id: "mobil" }, options: ["araba", "okul", "kalem"], answerParts: ["araba"], image: image("araba"), hint: [{ en: "The picture has wheels. Choose the long, even word.", id: "Gambar ini punya roda. Pilih kata yang panjang dan rata." }], learnWhy: guide("Araba means car.", "Araba berarti mobil.", "Each a stays open: a-ra-ba.", "Setiap a tetap terbuka: a-ra-ba.", "Do not let an a turn into ey.", "Jangan ubah a menjadi ey.", ["Tap each part: a · ra · ba.", "Say araba."], ["Ketuk setiap bagian: a · ra · ba.", "Ucapkan araba."]) }
];

const plurals: Lesson[] = [
  { id: "plural_evler", kind: "builder", prompt: { en: "Build houses", id: "Susun rumah-rumah" }, finalWord: "evler", meaning: { en: "houses", id: "rumah-rumah" }, options: ["ev", "ler", "lar"], answerParts: ["ev", "ler"], image: image("ev"), verifiedAudio: "/audio/pronunciation_tr_evler.mp3", hint: [{ en: "Start with ev. Then add the block for more than one.", id: "Mulai dengan ev. Lalu tambahkan blok untuk lebih dari satu." }, { en: "Use ler here, not lar.", id: "Gunakan ler di sini, bukan lar." }], learnWhy: guide("Ev + ler makes evler: more than one house.", "Ev + ler menjadi evler: lebih dari satu rumah.", "Hear ev first, then a light ler.", "Dengarkan ev dulu, lalu ler yang ringan.", "Do not choose lar after ev in this word.", "Jangan memilih lar setelah ev pada kata ini.", ["Build ev + ler.", "Listen after you solve."], ["Susun ev + ler.", "Dengarkan setelah kamu menyelesaikannya."]) },
  { id: "plural_kitaplar", kind: "builder", prompt: { en: "Build books", id: "Susun buku-buku" }, finalWord: "kitaplar", meaning: { en: "books", id: "buku-buku" }, options: ["kitap", "lar", "ler"], answerParts: ["kitap", "lar"], image: image("kitap"), verifiedAudio: "/audio/pronunciation_tr_kitaplar.mp3", hint: [{ en: "Keep kitap whole, then add the plural block.", id: "Pertahankan kitap utuh, lalu tambahkan blok jamak." }, { en: "Use lar after the a in kitap.", id: "Gunakan lar setelah a di kitap." }], learnWhy: guide("Kitap + lar makes kitaplar: more than one book.", "Kitap + lar menjadi kitaplar: lebih dari satu buku.", "The final p stays in this plural word.", "P terakhir tetap ada dalam kata jamak ini.", "Do not use ler after kitap here.", "Jangan gunakan ler setelah kitap di sini.", ["Say kitap.", "Add lar."], ["Ucapkan kitap.", "Tambahkan lar."]) },
  { id: "plural_arabalar", kind: "builder", prompt: { en: "Build cars", id: "Susun mobil-mobil" }, finalWord: "arabalar", meaning: { en: "cars", id: "mobil-mobil" }, options: ["araba", "lar", "ler"], answerParts: ["araba", "lar"], image: image("araba"), verifiedAudio: "/audio/pronunciation_tr_arabalar.mp3", hint: [{ en: "Start with araba. Add the block for more than one.", id: "Mulai dengan araba. Tambahkan blok untuk lebih dari satu." }], learnWhy: guide("Araba + lar makes arabalar: more than one car.", "Araba + lar menjadi arabalar: lebih dari satu mobil.", "Let the last a lead naturally into lar.", "Biarkan a terakhir menyambung alami ke lar.", "Do not add a separate word.", "Jangan tambahkan kata terpisah.", ["Say araba.", "Add lar."], ["Ucapkan araba.", "Tambahkan lar."]) }
];

const meaning: Lesson[] = [
  { id: "meaning_kitabimda", kind: "builder", prompt: { en: "Build in my book", id: "Susun di buku saya" }, finalWord: "kitabımda", meaning: { en: "in my book", id: "di buku saya" }, options: ["kitab", "ım", "da", "im", "ta"], answerParts: ["kitab", "ım", "da"], image: image("kitap"), hint: [{ en: "The book block changes to kitab before the next small blocks join.", id: "Blok buku berubah menjadi kitab sebelum blok kecil berikutnya bergabung." }, { en: "Build the three blocks from left to right.", id: "Susun tiga blok dari kiri ke kanan." }], learnWhy: guide("Kitap changes to kitab before ım and da join: kitab + ım + da.", "Kitap berubah menjadi kitab sebelum ım dan da bergabung: kitab + ım + da.", "Hear one smooth word, not three separate words.", "Dengarkan satu kata yang mulus, bukan tiga kata terpisah.", "Do not build kitap + im. The safe build form is kitab + ım.", "Jangan menyusun kitap + im. Bentuk susun yang benar adalah kitab + ım.", ["Say kitab.", "Add ım, then da."], ["Ucapkan kitab.", "Tambahkan ım, lalu da."]) },
  { id: "meaning_evde", kind: "builder", prompt: { en: "Build at home", id: "Susun di rumah" }, finalWord: "evde", meaning: { en: "at home", id: "di rumah" }, options: ["ev", "de", "da", "ler"], answerParts: ["ev", "de"], image: image("ev"), hint: [{ en: "Use the house word, then add the place block.", id: "Gunakan kata rumah, lalu tambahkan blok tempat." }], learnWhy: guide("Ev + de makes evde: at or in the house.", "Ev + de menjadi evde: di rumah.", "Hear ev and de as one connected word.", "Dengarkan ev dan de sebagai satu kata yang tersambung.", "Do not add a second word for in.", "Jangan tambahkan kata kedua untuk di.", ["Build ev + de.", "Say evde."], ["Susun ev + de.", "Ucapkan evde."]) },
  { id: "meaning_arabam", kind: "builder", prompt: { en: "Build my car", id: "Susun mobil saya" }, finalWord: "arabam", meaning: { en: "my car", id: "mobil saya" }, options: ["araba", "m", "n", "sı"], answerParts: ["araba", "m"], image: image("araba"), hint: [{ en: "Start with araba. Add the small m sound.", id: "Mulai dengan araba. Tambahkan bunyi m kecil." }], learnWhy: guide("Araba + m makes arabam: my car.", "Araba + m menjadi arabam: mobil saya.", "After the last a, hear only a small m.", "Setelah a terakhir, dengarkan hanya m kecil.", "Do not add a separate word for my.", "Jangan menambahkan kata terpisah untuk saya.", ["Say araba.", "Add m."], ["Ucapkan araba.", "Tambahkan m."]) }
];

export const TOPICS: Topic[] = [
  { id: "first-words", title: { en: "First useful words", id: "Kata pertama yang berguna" }, description: { en: "House, book, car — words you can picture.", id: "Rumah, buku, mobil — kata yang bisa kamu bayangkan." }, level: 1, gradient: "sky", lessons: roots },
  { id: "more-than-one", title: { en: "More than one", id: "Lebih dari satu" }, description: { en: "Build three everyday plural words.", id: "Susun tiga kata jamak sehari-hari." }, level: 2, gradient: "sun", lessons: plurals },
  { id: "meaning-builders", title: { en: "Build meanings", id: "Susun makna" }, description: { en: "Watch small blocks create a bigger idea.", id: "Lihat blok kecil membentuk ide yang lebih besar." }, level: 3, gradient: "mint", lessons: meaning }
];
export const ALL_LESSONS = TOPICS.flatMap((topic) => topic.lessons.map((lesson) => ({ ...lesson, topicId: topic.id })));
export const lessonById = (id: string) => ALL_LESSONS.find((lesson) => lesson.id === id);
