import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { V1_PARITY_BASELINE } from "../src/content/v1-parity-baseline";

const targetRoot = resolve(process.cwd(), "public/audio");
const sourceFiles = [...V1_PARITY_BASELINE.audioFiles];
const migratedFiles = existsSync(targetRoot) ? readdirSync(targetRoot).filter((name) => name.endsWith(".mp3")).sort() : [];
const verifiedPaths = V1_PARITY_BASELINE.verifiedAudioPaths.map((path) => path.replace(/^audio\//, "")).sort();
const missing = sourceFiles.filter((name) => !migratedFiles.includes(name));
const missingVerified = verifiedPaths.filter((name) => !migratedFiles.includes(name));
const markdown = `# Audio Migration

> Generated by \`pnpm audio:migration-report\` from the committed V1 audio/verification baseline and V2 public audio directory. Regenerate the baseline only after a verified audit of the read-only V1 repository.

| Measure | Count |
| --- | ---: |
| V1 total MP3 files | ${sourceFiles.length} |
| V1 owner-verified recordings | ${verifiedPaths.length} |
| V2 migrated MP3 files | ${migratedFiles.length} |
| V2 migrated owner-verified recordings | ${verifiedPaths.length - missingVerified.length} |
| Missing V1 files | ${missing.length} |
| Intentionally excluded V1 files | 0 |
| Synthetic files | 0 |

## Verification preservation

Owner-approved recordings retain the \`owner_verified\` status only when their path appears in the V1 baseline. Remaining migrated recordings are explicitly represented as \`human_unverified\`; they are not silently upgraded.

## Missing files

${missing.length ? missing.map((name) => `- \`${name}\``).join("\n") : "None."}

## Missing owner-verified files

${missingVerified.length ? missingVerified.map((name) => `- \`${name}\``).join("\n") : "None."}
`;
writeFileSync(resolve(process.cwd(), "docs/AUDIO-MIGRATION.md"), markdown);
console.log(JSON.stringify({ source: sourceFiles.length, verified: verifiedPaths.length, migrated: migratedFiles.length, missing: missing.length, missingVerified: missingVerified.length }, null, 2));
if (missing.length || missingVerified.length) process.exit(1);
