import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

const v1Root = resolve(process.cwd(), "../source-turkish-is-easy");
const registry = await import(pathToFileURL(resolve(v1Root, "js/audioRegistry.js")).href) as { audioAuditRows: () => Array<{ path: string; pronunciationVerified: boolean; intentionalNoAudio: boolean }> };
const sourceRoot = resolve(v1Root, "audio");
const targetRoot = resolve(process.cwd(), "public/audio");
const sourceFiles = readdirSync(sourceRoot).filter((name) => name.endsWith(".mp3")).sort();
const migratedFiles = existsSync(targetRoot) ? readdirSync(targetRoot).filter((name) => name.endsWith(".mp3")).sort() : [];
const verifiedPaths = [...new Set(registry.audioAuditRows().filter((row) => row.pronunciationVerified).map((row) => row.path.replace(/^audio\//, "")))].sort();
const missing = sourceFiles.filter((name) => !migratedFiles.includes(name));
const missingVerified = verifiedPaths.filter((name) => !migratedFiles.includes(name));
const markdown = `# Audio Migration\n\n> Generated by \`pnpm audio:migration-report\` from the read-only V1 audio directory, V1 verification registry, and V2 public audio directory.\n\n| Measure | Count |\n| --- | ---: |\n| V1 total MP3 files | ${sourceFiles.length} |\n| V1 owner-verified recordings | ${verifiedPaths.length} |\n| V2 migrated MP3 files | ${migratedFiles.length} |\n| V2 migrated owner-verified recordings | ${verifiedPaths.length - missingVerified.length} |\n| Missing V1 files | ${missing.length} |\n| Intentionally excluded V1 files | 0 |\n| Synthetic files | 0 |\n\n## Verification preservation\n\nOwner-approved recordings retain the \`owner_verified\` status only when their path appears in the V1 registry. Remaining migrated recordings are explicitly represented as \`human_unverified\`; they are not silently upgraded.\n\n## Missing files\n\n${missing.length ? missing.map((name) => `- \`${name}\``).join("\n") : "None."}\n\n## Missing owner-verified files\n\n${missingVerified.length ? missingVerified.map((name) => `- \`${name}\``).join("\n") : "None."}\n`;
writeFileSync(resolve(process.cwd(), "docs/AUDIO-MIGRATION.md"), markdown);
console.log(JSON.stringify({ source: sourceFiles.length, verified: verifiedPaths.length, migrated: migratedFiles.length, missing: missing.length, missingVerified: missingVerified.length }, null, 2));
if (missing.length || missingVerified.length) process.exit(1);
