import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

type SourceTopic = { id: string; title: { en: string; id: string }; type: string };
type SourceLesson = { id: string; topicId?: string; audio?: string; mainAudio?: string; exampleAudio?: string; contrastAudio?: string; extraExamples?: Array<{ audio?: string }> };

const v1Root = resolve(process.cwd(), "../source-turkish-is-easy");
const source = await import(pathToFileURL(join(v1Root, "js/lessonData.js")).href) as {
  TOPICS: SourceTopic[]; allLessonItems: () => SourceLesson[];
};
const sourceAudio = await import(pathToFileURL(join(v1Root, "js/audioRegistry.js")).href) as {
  audioAuditRows: () => Array<{ path: string; pronunciationVerified: boolean; intentionalNoAudio: boolean }>;
};
const sourceProfiles = await import(pathToFileURL(join(v1Root, "js/profiles.js")).href) as { PROFILES: unknown[] };
const v2 = await import("../src/content/curriculum");

const v1Topics = source.TOPICS;
const v1Items = source.allLessonItems();
const v2Topics = v2.TOPICS as Array<{ id: string; title: { en: string; id: string }; lessons: Array<{ id: string; verifiedAudio?: string }> }>;
const v2Items = v2.ALL_LESSONS as Array<{ id: string; verifiedAudio?: string }>;
const v1AudioRows = sourceAudio.audioAuditRows();
const uniqueV1Audio = [...new Set(v1AudioRows.filter((row) => row.path).map((row) => row.path))];
const verifiedV1Audio = [...new Set(v1AudioRows.filter((row) => row.pronunciationVerified).map((row) => row.path))];
const v1AudioRoot = resolve(v1Root, "audio");
const v1AudioFiles = readdirSync(v1AudioRoot).filter((name) => name.endsWith(".mp3"));
const v2AudioRoot = resolve(process.cwd(), "public/audio");
const v2AudioFiles = existsSync(v2AudioRoot) ? readdirSync(v2AudioRoot).filter((name) => name.endsWith(".mp3")) : [];
const missingTopics = v1Topics.filter((topic) => !v2Topics.some((candidate) => candidate.id === topic.id)).map((topic) => topic.id);
const missingItems = v1Items.filter((item) => !v2Items.some((candidate) => candidate.id === item.id)).map((item) => item.id);
const missingVerifiedAudio = verifiedV1Audio.filter((path) => !existsSync(resolve(process.cwd(), "public", path)));
const status = (v2Value: number, v1Value: number) => v2Value >= v1Value ? "PASS" : "FAIL";

const inventory = {
  generatedAt: new Date().toISOString(),
  v1: { topics: v1Topics.length, nonReviewItems: v1Items.length, audioFiles: v1AudioFiles.length, referencedAudioMappings: uniqueV1Audio.length, ownerVerifiedAudio: verifiedV1Audio.length, profiles: sourceProfiles.PROFILES.length },
  v2: { topics: v2Topics.length, items: v2Items.length, audioFiles: v2AudioFiles.length, ownerVerifiedAudio: new Set(v2Items.flatMap((item) => item.verifiedAudio ? [item.verifiedAudio] : [])).size, profiles: (v2.PROFILES as unknown[]).length },
  missingTopics, missingItems, missingVerifiedAudio,
  parity: { topics: status(v2Topics.length, v1Topics.length), items: status(v2Items.length, v1Items.length), sourceAudioFiles: status(v2AudioFiles.length, v1AudioFiles.length), ownerVerifiedAudio: status(new Set(v2Items.flatMap((item) => item.verifiedAudio ? [item.verifiedAudio] : [])).size, verifiedV1Audio.length) },
};

mkdirSync(resolve(process.cwd(), "docs"), { recursive: true });
writeFileSync(resolve(process.cwd(), "docs/v1-v2-parity.json"), `${JSON.stringify(inventory, null, 2)}\n`);
const table = [
  ["Topics", inventory.v1.topics, inventory.v2.topics, inventory.parity.topics],
  ["Non-review learning items", inventory.v1.nonReviewItems, inventory.v2.items, inventory.parity.items],
  ["Audio MP3 assets", inventory.v1.audioFiles, inventory.v2.audioFiles, inventory.parity.sourceAudioFiles],
  ["Referenced V1 audio mappings", inventory.v1.referencedAudioMappings, inventory.v2.audioFiles, inventory.parity.sourceAudioFiles],
  ["Owner-verified audio mappings", inventory.v1.ownerVerifiedAudio, inventory.v2.ownerVerifiedAudio, inventory.parity.ownerVerifiedAudio],
  ["Profiles", inventory.v1.profiles, inventory.v2.profiles, status(inventory.v2.profiles, inventory.v1.profiles)],
].map((row) => `| ${row.join(" | ")} |`).join("\n");
writeFileSync(resolve(process.cwd(), "docs/V1-V2-PARITY.md"), `# V1 → V2 Parity Inventory\n\n> This report is generated by \`pnpm parity:report\` from the read-only V1 repository and current V2 source. It records the actual recovery gap; it is not a claim of release readiness.\n\n| Capability | V1 | Current V2 | Status |\n| --- | ---: | ---: | --- |\n${table}\n\n## Required V1 topics not yet represented\n\n${missingTopics.length ? missingTopics.map((id) => `- \`${id}\``).join("\n") : "None."}\n\n## Missing V1 learning items\n\n${missingItems.length} items are not yet present in V2. The JSON inventory contains their exact IDs.\n\n## Missing owner-verified audio\n\n${missingVerifiedAudio.length ? missingVerifiedAudio.map((path) => `- \`${path}\``).join("\n") : "None."}\n\n## Release determination\n\n**${Object.values(inventory.parity).every((result) => result === "PASS") ? "PARITY PASS" : "PARITY FAIL"}** — recovery work remains mandatory until all baseline rows pass without an owner-approved exclusion.\n`);

console.log(JSON.stringify({ report: "docs/V1-V2-PARITY.md", ...inventory }, null, 2));
if (process.env.PARITY_STRICT === "1" && Object.values(inventory.parity).some((result) => result === "FAIL")) process.exit(1);
